language: node_js
node_js:
  - "8"
services:
  - docker
script:
  - docker build -t v2land-nginx:latest .
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
